export const FETCH_DATA = 'FETCH_DATA';
export const FETCH_DATA_REJECTED = 'FETCH_DATA_REJECTED';
export const FETCH_DATA_FULFILLED = 'FETCH_DATA_FULFILLED';
export const SET_FOCUS = 'SET_FOCUS';
export const SET_NUMBER = 'SET_NUMBER';